### ISSUE TITLE
All Crashes not Reporting

### ISSUE THREAD

**Issue by sfxworks** [distriqt/ANE-Firebase#108]
On the field testing, a worker came back to me and reported his application crashed. Upon inspection, I was relying on a single thread to process a long list with a lot of bitmaps stored in memory. This leads me to believe their application crashed due to an outOfMemoryError.

##### Expected behaviour
Fatal Crash would show up in Firebase.

##### Actual behaviour
Fatal Crash does not show up in firebase. 

##### Environment 

- AIR SDK version: 25 
- Device OS: Android
- Device version: 7.0
- Development IDE: Animate
- Development OS: Windows

##### Logs

I believe that this was caused by a lack of memory and other processes in the android system at the time. According to the worker, the scroller was active with multiple images loaded. The user when to another section that takes, on a single thread, ~4 seconds to parse. The user was, however, prompted with the "Application not Responding" screen and hit "Wait" to let it keep processing. So, it could be something else entirely that made it crash.

**Comment by marchbold** [comment]
Out of memory issues often aren't caught by crash reporters. This is due to the way the system is terminating these applications in these cases. It's not a normal crash as such and the hardest to report. 

Firebase should be able to catch `OutOfMemoryError` errors and I can't see any reason why it wouldn't be with the ANE. 

Can you confirm this is the error your application is generating?

**Comment by sfxworks** [comment]
I cannot. This has only happened once. This is what I am guessing given the description of activity and my knowledge of what goes on behind the scenes.

By process of elimination I am about 70% sure though. I'm not sure it was a script timeout if the OS eventually does something with it. I know the script time limit for AIR was set to 15 but I didn't see any of those. The wait period went well beyond 15 seconds.

**Comment by marchbold** [comment]
Not really sure what to do then. 

If it's not an issue we can replicate or even know what caused it I'm not sure how to investigate.

**Comment by sfxworks** [comment]
I will see what I can do to replicate it. The code that was causing the issue is just switched off so I might be able to replicate it when I'm repairing.

**Comment by marchbold** [comment]
Thanks, anything you can provide that would replicate the issue would allow us to investigate.

**Comment by vikreed** [comment]
Same is happening with us. APP hangs many times(End up saying - Your App is not Responding do you want to Wait or Close app.), And when I go to Firebase Crash Reports, I don't see any Crashes listed.  

This is quite frequent. My only worry is as we are not getting anything clue of what happened, I have no way to fix issues. Is there any other way to identify Crashes? I mean even if we are not getting it listed on Firebase, is there a way to get a report next time app is opened?

Thanks, 
Aseem

**Comment by marchbold** [comment]
Hi,

"Application Not Responding" (ANR) errors are in a similar category as memory errors and are often not handled by crash analytics. I believe Firebase Crash reports are more focussed around exceptions than ANR / OOM errors. 

Are you sure these are handled by Firebase? I can't find any reference at the moment that says they are.

**Comment by vikreed** [comment]
No, I have no idea about it. I was looking for some Inputs from you.

Guess I framed my question wrong.  Shall reframe it this way - 
1) What all kind of Exceptions is not handled by  Firebase Crash Reporting.
2) And What are the alternates available to handle those exceptions?

**Comment by vikreed** [comment]
how about this - https://github.com/distriqt/ANE-Exceptions

But I don't see any documentation for it.

Thanks, 
Aseem

**Comment by vikreed** [comment]
Ahh I see, Documentation is available in first page itself.

**Comment by marchbold** [comment]
As far as I'm aware, Firebase Crash reporting will handle all exceptions, just not the other application errors that result in system terminations, such as "Application Not Responding" and "Out of Memory" errors. Those errors are terminations by the system due to either timeouts in response of the ui or memory consumption.

The Exceptions ANE is a wrapper for the global uncaught exception handler. I wouldn't expect it to catch anything more than Firebase.

ANR's should be reported in the Google Play console for your application.

**Comment by vikreed** [comment]
I have faced many ANR in my development built, and in the play store, I can see no entry for same. 

But in the production build, I can see few ANR's(something to start with). Though I cannot make any sense out of it.  :) 
Any HeadStart for this?

Thanks, 
Aseem

**Comment by vikreed** [comment]
Ok, I had a look at ANR's.  There are few ANR's in Google Play. Its says 

Input dispatching timed out (Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it. Outbound queue length: 0. Wait queue length: 10.), VisibleToUser

I can also see in all of these ANRs, our FirebaseDatabase Tread is in TimedWaiting State. Could you please see if this is something to do with FirebaseDatabase Thread. 

[Input dispatching timed out  - ANR Log.txt](https://github.com/distriqt/ANE-Firebase/files/1398202/Input.dispatching.timed.out.-.ANR.Log.txt)


Regards, 
Aseem

**Comment by sfxworks** [comment]
My ANR report also showed up in the google play services thread. Noting that ANRs show up there and closing my issue on this technicality.
