### ISSUE TITLE
Android crash OnFrameMetricsAvailableListener 

### ISSUE THREAD

**Issue by railnation** [distriqt/ANE-Firebase#162]
A quick google search makes me think that this could be a firebase-related bug.

https://stackoverflow.com/questions/50281141/attempt-to-remove-onframemetricsavailablelistener-that-was-never-added

##### Expected behaviour
User watches a video using the fyber mobile-sdk adobe-air. After watching the first video, user starts the second video.

##### Actual behaviour
App crashes with "FATAL EXCEPTION: main" when starting the second video. 
java.lang.RuntimeException: Unable to stop activity {com.traviangames.railnationworld/com.traviangames.railnationworld.AppEntry}: java.lang.IllegalArgumentException: attempt to remove OnFrameMetricsAvailableListener that was never added

##### Environment 

- AIR SDK version: 29.0
- Device OS: Android
- Device version:  7.1.1
- Development IDE: FDT
- Development OS: Windows 10

##### Logs
Device logs if relevant
[log.txt](https://github.com/distriqt/ANE-Firebase/files/2200711/log.txt)

**Comment by marchbold** [comment]
Hi, Yeah I believe you are right, this looks like an issue internal to the Firebase SDK. Will have to see if the next update resolves it.

**Comment by railnation** [comment]
Do you know when the next release will happen? It is very import because we have a released version with this bug.

**Comment by marchbold** [comment]
We are working on the v16.x.x release, we expect to release in August.

**Comment by sangupandi** [comment]
How to fix this issue.. Any updates?

**Comment by marchbold** [comment]
We are still working on this update. It has been delayed so we can incorporate the Firestore ANE first.

**Comment by lu769257351** [comment]
我这边用的16.x.x还是存在同样的问题

**Comment by nomankhan18** [comment]
I am using latest Firebase Performance SDK and crashing in Android Oreo and above. 
Crash Message showing in logcat is:
 attempt to remove OnFrameMetricsAvailableListener that was never added.

Here is my app gradle config

**App-level build.gradle** 

 dependencies {
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'com.google.firebase:firebase-plugins:1.1.5'
    }

**app module level build.gradle**

 dependencies {
    implementation 'com.google.firebase:firebase-perf:16.2.2'
}
apply plugin: 'com.google.gms.google-services'
apply plugin: 'newrelic'
apply plugin: 'com.google.firebase.firebase-perf'

**Comment by marchbold** [comment]
@nomankhan18 This repository is for using the Firebase ANEs not the Android libraries. Best asking issues with integrating the Firebase Android SDK in the Google forums.

**Comment by YuriyBlinov** [comment]
We have recently migrated to Firebase from GA and got the same exception. Any updates?

**Comment by marchbold** [comment]
Can you post the information about your exception?

**Comment by esg-grant** [comment]
We're running into a similar problem, though slightly different.  In our case, the crash occurs when returning from the second ad.  So, our repro steps are basically:
- Launch app
- Watch ad
- Return to game from viewing ad
- Watch second ad
- Crash when returning to game after viewing ad

We're using the latest version of Firebase (v2.4.078 from 2019.03.11)

Here's the info for the exception we're getting.

Fatal Exception: java.lang.RuntimeException
Unable to stop activity {air.com.**************.AppEntry}: java.lang.IllegalArgumentException: attempt to remove OnFrameMetricsAvailableListener that was never added
android.app.ActivityThread.callActivityOnStop (ActivityThread.java:4189)
android.app.ActivityThread.performStopActivityInner (ActivityThread.java:4159)
android.app.ActivityThread.handleStopActivity (ActivityThread.java:4234)
android.app.servertransaction.StopActivityItem.execute (StopActivityItem.java:41)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:145)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1816)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:6718)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)


Caused by java.lang.IllegalArgumentException
attempt to remove OnFrameMetricsAvailableListener that was never added
android.view.View.removeFrameMetricsListener (View.java:6504)
android.view.Window.removeOnFrameMetricsAvailableListener (Window.java:886)
android.support.v4.app.FrameMetricsAggregator$FrameMetricsApi24Impl.remove (FrameMetricsAggregator.java:432)
android.support.v4.app.FrameMetricsAggregator.remove (FrameMetricsAggregator.java:245)
com.google.firebase.perf.internal.zza.onActivityStopped (Unknown Source:64)
android.app.Application.dispatchActivityStopped (Application.java:257)
android.app.Activity.onStop (Activity.java:1915)
air.com.eastsidegamestudio.PFGrassRoots.AppEntry.onStop (AppEntry.java:444)
android.app.Instrumentation.callActivityOnStop (Instrumentation.java:1432)
android.app.Activity.performStop (Activity.java:7375)
android.app.ActivityThread.callActivityOnStop (ActivityThread.java:4181)
android.app.ActivityThread.performStopActivityInner (ActivityThread.java:4159)
android.app.ActivityThread.handleStopActivity (ActivityThread.java:4234)
android.app.servertransaction.StopActivityItem.execute (StopActivityItem.java:41)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:145)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1816)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:6718)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)


Is there a workaround?

**Comment by marchbold** [comment]
@esg-grant What ad ANE are you using? 

Do you have `android:hardwareAccelerated="true"` in your application descriptor's manifest additions?

**Comment by esg-grant** [comment]
We're using IronSource (latest version).

We have the following in our manifest additions:

                    <activity           android:name="com.ironsource.sdk.controller.ControllerActivity"
                                        android:configChanges="orientation|screenSize"
                                        android:hardwareAccelerated="true" />
                    <activity           android:name="com.ironsource.sdk.controller.InterstitialActivity"
                                        android:configChanges="orientation|screenSize"
                                        android:hardwareAccelerated="true"
                                        android:theme="@android:style/Theme.Translucent" />
                    <activity           android:name="com.ironsource.sdk.controller.OpenUrlActivity"
                                        android:configChanges="orientation|screenSize"
                                        android:hardwareAccelerated="true"
                                        android:theme="@android:style/Theme.Translucent" />

**Comment by marchbold** [comment]
What about the hardwareAccelerated flag on the application tag though?

**Comment by esg-grant** [comment]
We do not appear to have it on the application tag

**Comment by marchbold** [comment]
Could you try adding it? I have seen reports that not adding that can cause this issue.

**Comment by esg-grant** [comment]
Ah.  Sorry for the late reply.  We've added it yesterday and preliminary indications are that it's solved the issue.  However, we're waiting for QA to do a thorough pass before the final determination.

**Comment by marchbold** [comment]
Great, let me know how it goes.

**Comment by esg-grant** [comment]
Apologies for the huge delay.  It passed through QA and appears to work fine.  Thanks for your help!

**Comment by marchbold** [comment]
Excellent, thanks for getting back to us!
