### ISSUE TITLE
GoogleService failed to initialize using delayed configuration

### ISSUE THREAD

**Issue by mwelk** [distriqt/ANE-Firebase#20]
I'm using version 2016.11.22 together with delayed configuration on android
While starting up, I can see, that the configuration was read successfully:
```
com.distriqt.Firebase: FirebaseController::initialiseApp(): Using supplied options
com.distriqt.Firebase: FirebaseController::initialiseApp(): apiKey = AAAA
com.distriqt.Firebase: FirebaseController::initialiseApp(): googleAppID = BBBB
com.distriqt.Firebase: FirebaseController::initialiseApp(): databaseURL = CCCC
com.distriqt.Firebase: FirebaseController::initialiseApp(): gcmSenderID = DDDD
com.distriqt.Firebase: FirebaseController::initialiseApp(): storageBucket = EEEE
```
But then it failed initializing the GoogleService:
```
FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
FA      : App measurement is starting up, version: 9877
FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
FA      : Debug-level message logging enabled
FA      : AppMeasurement singleton hash: 197556196
FA      : GoogleService failed to initialize, status: 10, Missing google app id value from from string resources with name google_app_id.
FA      : Scheduler not set. Not logging error/warn.
FA      : To enable faster debug mode event logging run:
FA      :   adb shell setprop firebase.analytics.debug-mode MY_APP_ID
FA      : Registered activity lifecycle callback
FA      : Measurement Service called without google_app_id
FA      : Uploading is not possible. App measurement disabled
```
Do I need to set the google_app_id manually somewhere else?

Thanks and best regards,
Matthias

**Comment by marchbold** [comment]
The delayed initialisation is still quite unreliable and we definitely recommend using the resources method if possible. 

We are looking into ways of making it more consistent.

**Comment by mwelk** [comment]
Ok, I will try the resource method.

Thanks,
Matthias

**Comment by mwelk** [comment]
I managed to get it working with the resource method, thanks!

We have several apps linked to our firebase project. Could it be, that the delayed initialization can not handle this setup at the moment (multiple clients in the json file)?

Thanks and best regards,
Matthias

**Comment by marchbold** [comment]
The json file isn't actually read by Firebase at all. It's actually just a helper file that Android Studio uses to generate the resource xml. If you saw the correct settings being traced out that's our process of reading the file and pulling out the matching config for the current application package. 

What seems to be the issue is that some of the Firebase functionality starts before we have the chance to pass the configuration to it. Sometimes it recovers when we pass it the options however in some situations it seems to stop altogether. We are trying to isolate what's happening here and see if it's a fault with the way we are passing the params or a bug in the Firebase SDK. 

Glad you got it working using the resources method.
