### ISSUE TITLE
iOS Debugging

### ISSUE THREAD

**Issue by idzdigital** [distriqt/ANE-Firebase#238]
Is there any way to debug analytics in iOS?

**Comment by marchbold** [comment]
Not really, Firebase uses a compiler flag to enable analytics debugging on iOS which we can't use with AIR (or at least we haven't been able to figure out a way).

**Comment by marchbold** [comment]
https://firebase.google.com/docs/analytics/debugview

**Comment by marchbold** [comment]
You need to add a compiler flag `-FIRDebugEnabled`

**Comment by marchbold** [comment]
Apologies, has been several years since I've looked at this, yes it's a command line arg. 

What I meant is we haven't figured out a way to make AIR use command line args when debugging on iOS, but yes there are methods of running an ipa you have with the command line args, but it is outside our support.

But if you are familiar with idevicedebug this was working for us in the past:
```
idevicedebug run "com.distriqt.test" "-FIRDebugEnabled"
```
